/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Aida
 */
public class MockLandingPage extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static String filename;
	/**
     * Creates new form MockLandingPage
     */
    public MockLandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("View XML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Guidelines");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        
        JButton btnViewLog = new JButton("View Log");
        btnViewLog.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new DisplayLog().setVisible(true);
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jButton4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        						.addComponent(jButton3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        						.addComponent(jButton2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        						.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        					.addGap(639))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(btnViewLog, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jButton5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(29)
        			.addComponent(jButton1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton3)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton4)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton5)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnViewLog)
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        
    
    public void chooseMethod() {
		JFileChooser chooser = new JFileChooser();
		chooser.setDialogTitle("Select an XML file");
		
		int userSelection = chooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = chooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
        }
		
//        chooser.showOpenDialog(null);
//        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//        File file = chooser.getSelectedFile();
//        String filename = file.getAbsolutePath();
        
	}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
                      
                 try {
                    
//                    ArrayList<String> id = new ArrayList<String>();
//                    ArrayList<String> length = new ArrayList<String>();
//                    ArrayList name = new ArrayList();
//                    ArrayList classname = new ArrayList();
                    
//                    ArrayList<List<Object>> data = new ArrayList<List<Object>>();

                    DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
                    DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
                    Document doc = dBuilder.parse(filename);

                    doc.getDocumentElement().normalize();

	NodeList nList = doc.getElementsByTagName("isofield");
        Object[][] ob = new Object[nList.getLength()][4];
        
	for (int temp = 0; temp < nList.getLength(); temp++) {

		Node nNode = nList.item(temp);

		System.out.println("\nCurrent Element :" + nNode.getNodeName());

		if (nNode.getNodeType() == Node.ELEMENT_NODE) {

			Element eElement = (Element) nNode;
                        
//                        data.add(Arrays.asList(eElement.getAttribute("id"), eElement.getAttribute("length"), 
//                                eElement.getAttribute("name"), eElement.getAttribute("class")));
                            ob[temp][0] = eElement.getAttribute("id");                           
                            ob[temp][1] = eElement.getAttribute("length");
                            ob[temp][2] = eElement.getAttribute("name");
                            ob[temp][3] = eElement.getAttribute("class");
                        
//			jTextArea1.append("\n\nMessage Id : " + eElement.getAttribute("id"));
//                        id.add(eElement.getAttribute("id"));
//                        
//                        jTextArea1.append("\nMessage Length : " + eElement.getAttribute("length"));
//                        length.add(eElement.getAttribute("length"));
//                        
//                        jTextArea1.append("\nMessage Name : " + eElement.getAttribute("name"));
//                        name.add(eElement.getAttribute("name"));
//                        
//                        jTextArea1.append("\nMessage Class : " + eElement.getAttribute("class"));
//                        classname.add(eElement.getAttribute("class"));
                        
//                        for(int i = 0; i < id.size(); i++) {
//                            System.out.println("Message ID : " + id.get(i));
//                        }
                        
		}
        }
        
//                    Object[][] ob = (Object[][])data.toArray();
                    
                    new DisplayTable(ob).setVisible(true); 
        
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(null,e);
                }

    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                new EditISO().setVisible(true);;
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
        new AddISO().setVisible(true);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            new ISO8583Table2();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        chooseMethod();
    	new DeleteISO();
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MockLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MockLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MockLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MockLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MockLandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
}
